import React,{useCallback,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,ChevronLeft,ChevronRight,Clock,FileText,History,PlayCircle,Save} from 'lucide-react';
import Navbar from '../../components/common/Navbar';
import {studentExamApi} from '../../api/studentExamApi';
import './studentExam.css';

const clock=(s)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const date=(v)=>v?new Intl.DateTimeFormat('vi-VN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';

export default function StudentExamWorkspace({currentUser,onNavigate,onViewProfile,onLogout}){
 const[tab,setTab]=useState('exams'),[exams,setExams]=useState([]),[history,setHistory]=useState([]),[attempt,setAttempt]=useState(null),[index,setIndex]=useState(0),[remaining,setRemaining]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{if(tab==='exams')setExams((await studentExamApi.list()).data?.content||[]);else setHistory((await studentExamApi.history()).data?.content||[]);}catch(e){setError(e.message)}finally{setLoading(false)}},[tab]);
 useEffect(()=>{if(!attempt)load()},[load,attempt]);
 useEffect(()=>{if(!attempt||attempt.status!=='in_progress')return undefined;setRemaining(attempt.remainingSeconds||0);const timer=setInterval(()=>setRemaining(v=>{if(v<=1){clearInterval(timer);studentExamApi.submit(attempt.attemptId).then(r=>setAttempt(r.data)).catch(e=>setError(e.message));return 0}return v-1}),1000);return()=>clearInterval(timer)},[attempt?.attemptId,attempt?.status]);
 const start=async(id)=>{setLoading(true);try{const r=await studentExamApi.start(id);setAttempt(r.data);setIndex(0)}catch(e){setError(e.message)}finally{setLoading(false)}};
 const openAttempt=async(id)=>{setLoading(true);try{setAttempt((await studentExamApi.attempt(id)).data);setIndex(0)}catch(e){setError(e.message)}finally{setLoading(false)}};
 const updateQuestion=(qid,patch)=>setAttempt(a=>({...a,questions:a.questions.map(q=>q.questionId===qid?{...q,...patch}:q)}));
 const saveAnswer=async(q,answers,note=q.note)=>{updateQuestion(q.questionId,{selectedAnswers:answers,note});setSaving(true);try{await studentExamApi.answer(attempt.attemptId,q.questionId,answers,note)}catch(e){setError(e.message)}finally{setSaving(false)}};
 const submit=async()=>{if(!window.confirm('Bạn có chắc muốn nộp bài? Sau khi nộp không thể sửa đáp án.'))return;setSaving(true);try{setAttempt((await studentExamApi.submit(attempt.attemptId)).data)}catch(e){setError(e.message)}finally{setSaving(false)}};
 const q=attempt?.questions?.[index];
 return <div className="se-page"><Navbar currentView="student_exams" currentUser={currentUser} onNavigate={onNavigate} onViewProfile={onViewProfile} onLogout={onLogout}/><main className="se-shell">
  {!attempt&&<><header className="se-hero"><div><span>JLPT MOCK EXAMINATION</span><h1>Luyện thi JLPT</h1><p>Làm đề theo QuestionSet, xem điểm số, đáp án và ghi lại nội dung cần ôn tập.</p></div><div className="se-tabs"><button className={tab==='exams'?'active':''} onClick={()=>setTab('exams')}><FileText size={17}/>Đề thi</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={17}/>Lịch sử & điểm</button></div></header>{error&&<div className="se-error">⚠ {error}</div>}{loading?<div className="se-state">Đang tải...</div>:tab==='exams'?<div className="se-grid">{exams.map(e=><article className="se-card" key={e.questionSetId}><div><span className="se-level">{e.jlptLevel}</span><span>{e.skillType}</span></div><h3>{e.title}</h3><p>{e.description||'Đề thi luyện tập JLPT'}</p><footer><span><Clock size={15}/>{e.durationMinutes} phút</span><span>{e.questionCount} câu</span><button disabled={!e.questionCount} onClick={()=>start(e.questionSetId)}><PlayCircle size={17}/>Làm bài</button></footer></article>)}</div>:<div className="se-history">{history.length===0?<div className="se-state">Bạn chưa có lượt thi nào.</div>:history.map(a=><button key={a.attemptId} onClick={()=>openAttempt(a.attemptId)}><div><strong>{a.title}</strong><span>{date(a.startedAt)} · {a.status}</span></div><b>{a.score??'—'} / {a.totalScore}</b></button>)}</div>}</>}
  {attempt&&q&&<><header className="se-exam-head"><button onClick={()=>setAttempt(null)}><ArrowLeft size={18}/></button><div><strong>{attempt.title}</strong><span>{attempt.jlptLevel} · {attempt.skillType}</span></div><div className={`se-timer ${remaining<300?'urgent':''}`}><Clock size={18}/>{attempt.status==='in_progress'?clock(remaining):attempt.status}</div>{attempt.status==='in_progress'&&<button className="se-submit" disabled={saving} onClick={submit}>Nộp bài</button>}</header>
   <div className="se-exam-layout"><aside><strong>Câu hỏi</strong><div>{attempt.questions.map((x,i)=><button className={`${i===index?'active':''} ${x.selectedAnswers?.length?'answered':''}`} onClick={()=>setIndex(i)} key={x.questionId}>{i+1}</button>)}</div><small>{attempt.questions.filter(x=>x.selectedAnswers?.length).length}/{attempt.questions.length} đã trả lời</small></aside>
   <section className="se-question"><div className="se-question-meta">Câu {index+1}/{attempt.questions.length} {saving&&<span>Đang lưu...</span>}</div><h2>{q.questionText}</h2><div className="se-options">{q.questionType==='fill_blank'?<input value={q.selectedAnswers?.[0]||''} disabled={attempt.status!=='in_progress'} onChange={e=>updateQuestion(q.questionId,{selectedAnswers:[e.target.value]})} onBlur={()=>saveAnswer(q,q.selectedAnswers||[])} placeholder="Nhập đáp án..."/>:q.choices.map((choice,i)=>{const multi=q.questionType==='multiple_select',checked=q.selectedAnswers?.includes(choice);return <label className={checked?'chosen':''} key={i}><input type={multi?'checkbox':'radio'} name={`q${q.questionId}`} checked={checked} disabled={attempt.status!=='in_progress'} onChange={()=>{const next=multi?(checked?q.selectedAnswers.filter(x=>x!==choice):[...(q.selectedAnswers||[]),choice]):[choice];saveAnswer(q,next)}}/><span>{String.fromCharCode(65+i)}</span>{choice}</label>})}</div>
   <label className="se-note"><span>📝 Ghi chú cho câu này</span><textarea value={q.note||''} disabled={attempt.status!=='in_progress'} onChange={e=>updateQuestion(q.questionId,{note:e.target.value})} onBlur={()=>saveAnswer(q,q.selectedAnswers||[],q.note)} placeholder="Ghi lại từ mới, ngữ pháp hoặc điều cần xem lại..."/></label>
   {attempt.status!=='in_progress'&&<div className={`se-result ${q.correct?'correct':'wrong'}`}><strong>{q.correct?<><CheckCircle2 size={18}/> Chính xác</>:'Chưa chính xác'}</strong><p>Đáp án đúng: {q.correctAnswers?.join(', ')||'—'}</p>{q.explanation&&<p><b>Giải thích:</b> {q.explanation}</p>}</div>}
   <footer className="se-nav"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ChevronLeft size={17}/>Trước</button><button disabled={index===attempt.questions.length-1} onClick={()=>setIndex(i=>i+1)}>Sau<ChevronRight size={17}/></button></footer></section></div>
   {attempt.status!=='in_progress'&&<section className="se-overall"><h3>Kết quả: {attempt.score}/{attempt.totalScore}</h3><label>Ghi chú sau bài thi<textarea value={attempt.reviewNote||''} onChange={e=>setAttempt(a=>({...a,reviewNote:e.target.value}))}/></label><button onClick={async()=>{setSaving(true);try{setAttempt((await studentExamApi.note(attempt.attemptId,attempt.reviewNote)).data)}finally{setSaving(false)}}}><Save size={16}/>Lưu ghi chú</button></section>}
  </>}
 </main></div>
}
