package com.example.base.controller.student_exam;
import com.example.base.dto.common.*; import com.example.base.dto.student_exam.request.*; import com.example.base.dto.student_exam.response.*; import com.example.base.security.UserPrincipal; import com.example.base.service.student_exam.StudentExamService;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/student-exams") @RequiredArgsConstructor @PreAuthorize("hasAnyAuthority('Student','ROLE_Student')")
public class StudentExamController { private final StudentExamService service;
 @GetMapping public ResponseEntity<ApiResponse<PageResponse<StudentExamSummaryResponse>>> exams(@PageableDefault(size=9,sort="updatedAt",direction=Sort.Direction.DESC) Pageable p){return ResponseEntity.ok(ApiResponse.success(service.listExams(p)));}
 @PostMapping("/{setId}/attempts") public ResponseEntity<ApiResponse<TestAttemptResponse>> start(@PathVariable Long setId,@AuthenticationPrincipal UserPrincipal u){return ResponseEntity.status(201).body(ApiResponse.success(service.start(setId,u)));}
 @GetMapping("/attempts/{id}") public ResponseEntity<ApiResponse<TestAttemptResponse>> get(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal u){return ResponseEntity.ok(ApiResponse.success(service.getAttempt(id,u)));}
 @PutMapping("/attempts/{id}/answers/{qid}") public ResponseEntity<ApiResponse<TestAttemptResponse>> answer(@PathVariable Long id,@PathVariable Long qid,@RequestBody SaveAnswerRequest r,@AuthenticationPrincipal UserPrincipal u){return ResponseEntity.ok(ApiResponse.success(service.saveAnswer(id,qid,r,u)));}
 @PostMapping("/attempts/{id}/submit") public ResponseEntity<ApiResponse<TestAttemptResponse>> submit(@PathVariable Long id,@AuthenticationPrincipal UserPrincipal u){return ResponseEntity.ok(ApiResponse.success(service.submit(id,u)));}
 @GetMapping("/history") public ResponseEntity<ApiResponse<PageResponse<TestAttemptResponse>>> history(@PageableDefault(size=10,sort="startedAt",direction=Sort.Direction.DESC) Pageable p,@AuthenticationPrincipal UserPrincipal u){return ResponseEntity.ok(ApiResponse.success(service.history(p,u)));}
 @PatchMapping("/attempts/{id}/note") public ResponseEntity<ApiResponse<TestAttemptResponse>> note(@PathVariable Long id,@Valid @RequestBody UpdateAttemptNoteRequest r,@AuthenticationPrincipal UserPrincipal u){return ResponseEntity.ok(ApiResponse.success(service.updateNote(id,r,u)));}
}
